AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  FileUploadedProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileUploadedProcessor
      Runtime: dotnet10
      Handler: FileUploadedProcessor::FileUploadedProcessor.Function::FunctionHandler
      CodeUri: ../FileUploadedProcessor
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::339245257062:role/lambda-file-processor-role

      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: mario-aws-file-storage-dev
            Events: s3:ObjectCreated:*